version: "3"

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - '6379:6379'

  publisher:
    build: ./services
    command: node publisher.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    depends_on: 
      - redis

  subscriber:
    build: ./services
    command: node subscriber.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    depends_on: 
      - redis
      
  