version: "3"

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - '6379:6379'

  publisher:
    build: ./services
    command: node publisher.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    depends_on: 
      - redis
    ports:
      - '3000:3000'
  
  device: 
    build: ./services
    command: node device.js
    environment:
      - HOST=publisher
    links:
      - publisher
    depends_on: 
      - publisher

  subscriber:
    build: ./services
    command: node subscriber.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    ports:
     - "8000:8000"
    depends_on: 
      - redis
  
  client:
    build: ./client
    links:
      - subscriber
    depends_on: 
      - subscriber
    ports:
     - "8100:80"
      
  