version: "3"

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - '6379:6379'
  
  publisherlb:
    image: 'dockercloud/haproxy:latest'
    links:
      - publisher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '3000:80'

  publisher:
    build: ./services
    command: node publisher.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    depends_on: 
      - redis
    expose:
      - 3000
  
  device: 
    build: ./services
    command: node device.js
    environment:
      - HOST=publisherlb
      - PUBLISHER_PORT=80
    links:
      - publisherlb
    depends_on: 
      - publisherlb

  subscriber:
    build: ./services
    command: node subscriber.js
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    ports:
     - "8000:8000"
    depends_on: 
      - redis
  
  client:
    build: ./client
    links:
      - subscriber
    depends_on: 
      - subscriber
    ports:
     - "8100:80"
      
  